<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>navigation_system</name>
  <version>0.0.0</version>
  <description>Package to handle wayfinding and route recording for DaVE
          We use waypoints to define places where we want the rover to go 
          and we use obstacles to define regions we cannot traverse on the way there
          
          the NAVnode uses a linked list for waypoints and a dynamic array for obstacles
          it allows for the creation of up to 5 preplanned routes for DaVE to take
          
          It communuicates with GNSS to get out current position
          It also can do obstacle avoidance (for software defined obstacles) and will have a built in mini-map display
  </description>
  <maintainer email="isaac.bobmeyer@gmail.com">isaac</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>


  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp_components</depend>
  <depend>navigation_interfaces</depend>
  <depend>serial_interfaces</depend>
  <depend>serial_communication</depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
